### PR TITLE
added password tests + pipeline

### PR DESCRIPTION
**Pull request by mattmoana**
added password tests and modified pipline

### CODE REVIEW

**Comment by Marusia2** [comment]
All password complexity testing passes. 
Accurate modifications have been made  to verify only URL tests in yml file

**Review by vladimir-tl — CHANGES_REQUESTED** [review]
2nd workflow missing

**Comment by mattmoana** [comment]
@vladimir-tl @Marusia2  added another yml file as per comment

**Comment by Marusia2** [comment]
Two pipelines have been set up for testing purposes: one is specifically for verifying passwords and the other is for confirming URLs, ensuring that only URL tests are conducted accurately in the original one :) 
well done ;)

**Pull request merged**
